// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGX9dxIekrBGwIdVQ3UZsJlou6sDKzQjQ',
    appId: '1:537418498095:android:69c5a1dd75c1acd0e486da',
    messagingSenderId: '537418498095',
    projectId: 'fir-bcd7a',
    storageBucket: 'fir-bcd7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8V8HNxgui814C9km5hApPza30nGDzanE',
    appId: '1:537418498095:ios:cc3de45720724351e486da',
    messagingSenderId: '537418498095',
    projectId: 'fir-bcd7a',
    storageBucket: 'fir-bcd7a.firebasestorage.app',
    androidClientId: '537418498095-43k97hhr33c8feksos13cho5doe1irtj.apps.googleusercontent.com',
    iosClientId: '537418498095-hsr6s004o8fdv9jqb8v73ganc156imo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyFriday',
  );
}
